[package]
name = "passage_wrapper"
version = "0.1.0"
description = "Passage Protocol wrapper vault: RWA-token in, composable pToken uit"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "passage_wrapper"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
